name: Build and Release Electron App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build and Package Electron app for Windows
        run: npm run electron-build -- --win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build and Package Electron app for Linux
        run: npm run electron-build -- --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    needs: [ build-windows, build-linux ]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.AppImage
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
